cd C:\Users\RAJ\eclipse-workspace\CollectionFrameWork\src\ArrayListConcept
java ArrayListIteration.java
java ArrayListDemo.java
java CombineArray.java
java GenericArrayList.java
java ListWithOtherClass.java
java SynchronizedArrayList.java
cd C:\Users\RAJ\eclipse-workspace\CollectionFrameWork\src\interfaceConcept
java Bank.java
java CUB.java
java SBI.java
cd C:\Users\RAJ\eclipse-workspace\CollectionFrameWork\src\sample
java Frequency.java
java InterfaceA.java
java PermutaionOfString.java
java Recursion.java
java RevEach.java
java Sample.java
